"""Database access layer — Cloudflare D1 (SQLite) backend.

Two modes:
- Production: Cloudflare D1 via its HTTP API (settings.d1_* configured).
- Local dev / tests without mocks: a local SQLite file (no D1 config set).

The client exposes a small query-builder interface that mirrors the
supabase-py client used previously (`db.table("users").select("*")
.eq("id", ...).single().execute()`), so service code keeps the same shape:
select / eq / in_ / not_.in_ / order / limit / single / insert / update /
delete / execute.

Value conventions:
- Booleans are stored as SQLite integers 0/1 and converted back to True/False
  on read for known boolean columns.
- Timestamps are ISO-8601 strings (UTC).
- Dicts/lists are stored as JSON strings.
- Row ids are UUID4 strings generated by the client on insert (same as the
  Postgres default did).
"""

import json
import sqlite3
import threading
import uuid
from datetime import datetime, timezone

import httpx

from app.config import settings

# Columns that hold booleans (SQLite stores 0/1) — converted on read.
_BOOLEAN_COLUMNS = {
    ("users", "is_active"),
    ("notifications", "is_read"),
}

# Tables whose rows carry an auto-updated `updated_at` column.
_UPDATED_AT_TABLES = {"users", "gatepass_requests", "notifications"}

# Tables whose rows carry `created_at` auto-filled on insert.
_CREATED_AT_TABLES = {"users", "gatepass_requests", "gate_logs", "notifications"}


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def _to_db_value(value):
    """Convert a Python value to something SQLite/D1 accepts as a parameter."""
    if isinstance(value, bool):
        return 1 if value else 0
    if isinstance(value, (dict, list)):
        return json.dumps(value)
    return value


def _from_db_value(table: str, column: str, value):
    """Convert a stored value back to a Python-friendly one."""
    if (table, column) in _BOOLEAN_COLUMNS and value in (0, 1):
        return bool(value)
    return value


class _Result:
    """Mimics supabase-py's PostgrestAPIResponse (only what we use: .data)."""

    def __init__(self, data):
        self.data = data


class _NotProxy:
    def __init__(self, query: "Query"):
        self._query = query

    def in_(self, column: str, values: list):
        self._query._not_in = (column, list(values))
        return self._query


class Query:
    """Accumulates filters/params and executes against the configured backend."""

    def __init__(self, backend: "Backend", table: str):
        self._backend = backend
        self._table = table
        self._select_cols: str | None = None
        self._filters: list[tuple[str, str, object]] = []  # ("eq"|"in", col, value)
        self._not_in: tuple[str, list] | None = None
        self._order_by: tuple[str, bool] | None = None  # (col, desc)
        self._limit_count: int | None = None
        self._single = False
        self._insert_payload: dict | None = None
        self._update_payload: dict | None = None
        self._delete = False

    # --- builder API (supabase-py compatible) ---

    def select(self, *args, **kwargs) -> "Query":
        if args:
            cols = args[0]
            self._select_cols = cols if isinstance(cols, str) else ",".join(args)
        return self

    def eq(self, column: str, value) -> "Query":
        self._filters.append(("eq", column, value))
        return self

    def in_(self, column: str, values: list) -> "Query":
        self._filters.append(("in", column, list(values)))
        return self

    @property
    def not_(self) -> _NotProxy:
        return _NotProxy(self)

    def order(self, column: str, desc: bool = False) -> "Query":
        self._order_by = (column, desc)
        return self

    def limit(self, count: int) -> "Query":
        self._limit_count = count
        return self

    def single(self) -> "Query":
        self._single = True
        self._limit_count = 1
        return self

    def insert(self, record: dict) -> "Query":
        self._insert_payload = dict(record)
        return self

    def update(self, data: dict) -> "Query":
        self._update_payload = dict(data)
        return self

    def delete(self) -> "Query":
        self._delete = True
        return self

    # --- SQL generation ---

    def _where_clause(self) -> tuple[str, list]:
        clauses: list[str] = []
        params: list = []

        for op, col, value in self._filters:
            if op == "eq":
                clauses.append(f'"{col}" = ?')
                params.append(_to_db_value(value))
            else:  # in
                if not value:
                    clauses.append("1 = 0")  # empty IN() matches nothing
                else:
                    placeholders = ", ".join("?" for _ in value)
                    clauses.append(f'"{col}" IN ({placeholders})')
                    params.extend(_to_db_value(v) for v in value)

        if self._not_in:
            col, values = self._not_in
            if values:
                placeholders = ", ".join("?" for _ in values)
                clauses.append(f'"{col}" NOT IN ({placeholders})')
                params.extend(_to_db_value(v) for v in values)

        return (" WHERE " + " AND ".join(clauses)) if clauses else "", params

    def _build_sql(self) -> tuple[str, list]:
        table = self._table
        where, params = self._where_clause()

        if self._insert_payload is not None:
            record = self._insert_payload
            if "id" not in record or not record["id"]:
                record["id"] = str(uuid.uuid4())
            if table in _CREATED_AT_TABLES and not record.get("created_at"):
                record["created_at"] = _now_iso()
            if table in _UPDATED_AT_TABLES and not record.get("updated_at"):
                record["updated_at"] = _now_iso()
            if table == "gate_logs" and not record.get("logged_at"):
                record["logged_at"] = _now_iso()

            cols = list(record.keys())
            col_sql = ", ".join(f'"{c}"' for c in cols)
            marks = ", ".join("?" for _ in cols)
            sql = f'INSERT INTO "{table}" ({col_sql}) VALUES ({marks}) RETURNING *'
            return sql, [_to_db_value(record[c]) for c in cols]

        if self._update_payload is not None:
            record = self._update_payload
            if table in _UPDATED_AT_TABLES:
                record.setdefault("updated_at", _now_iso())
            cols = list(record.keys())
            set_sql = ", ".join(f'"{c}" = ?' for c in cols)
            sql = f'UPDATE "{table}" SET {set_sql}{where} RETURNING *'
            params = [_to_db_value(record[c]) for c in cols] + params
            return sql, params

        if self._delete:
            return f'DELETE FROM "{table}"{where} RETURNING *', params

        cols = self._select_cols or "*"
        sql = f'SELECT {cols} FROM "{table}"{where}'
        if self._order_by:
            col, desc = self._order_by
            sql += f' ORDER BY "{col}" {"DESC" if desc else "ASC"}'
        if self._limit_count is not None:
            sql += f" LIMIT {int(self._limit_count)}"
        return sql, params

    # --- execution ---

    def execute(self) -> _Result:
        sql, params = self._build_sql()
        rows = self._backend.run(sql, params, self._table)
        if self._single:
            return _Result(rows[0] if rows else None)
        return _Result(rows)


class Backend:
    """Runs SQL against D1 (HTTP) or a local SQLite file."""

    def __init__(self):
        self._http: httpx.Client | None = None
        self._sqlite: sqlite3.Connection | None = None
        self._lock = threading.Lock()

    @property
    def is_d1(self) -> bool:
        return bool(
            settings.d1_account_id and settings.d1_database_id and settings.d1_api_token
        )

    def _get_http(self) -> httpx.Client:
        if self._http is None:
            self._http = httpx.Client(
                headers={"Authorization": f"Bearer {settings.d1_api_token}"},
                timeout=30.0,
            )
        return self._http

    def _get_sqlite(self) -> sqlite3.Connection:
        if self._sqlite is None:
            self._sqlite = sqlite3.connect(settings.local_db_path, check_same_thread=False)
            self._sqlite.row_factory = sqlite3.Row
            self._sqlite.execute("PRAGMA foreign_keys = ON")
            self._sqlite.commit()
        return self._sqlite

    def run(self, sql: str, params: list, table: str | None = None) -> list[dict]:
        if self.is_d1:
            rows = self._run_d1(sql, params)
        else:
            rows = self._run_sqlite(sql, params)

        if table:
            for row in rows:
                for key in list(row.keys()):
                    row[key] = _from_db_value(table, key, row[key])
        return rows

    def _run_d1(self, sql: str, params: list) -> list[dict]:
        url = (
            f"https://api.cloudflare.com/client/v4/accounts/{settings.d1_account_id}"
            f"/d1/database/{settings.d1_database_id}/query"
        )
        try:
            resp = self._get_http().post(url, json={"sql": sql, "params": params})
            resp.raise_for_status()
            body = resp.json()
        except Exception as e:
            raise RuntimeError(f"D1 request failed: {e}") from e

        if not body.get("success"):
            errors = body.get("errors") or []
            raise RuntimeError(f"D1 query error: {errors} — SQL: {sql[:200]}")

        results = (body.get("result") or [{}])[0].get("results", [])
        return [dict(r) for r in results]

    def _run_sqlite(self, sql: str, params: list) -> list[dict]:
        with self._lock:
            conn = self._get_sqlite()
            try:
                cur = conn.execute(sql, params)
                rows = [dict(r) for r in cur.fetchall()]
                conn.commit()
                return rows
            except sqlite3.Error as e:
                conn.rollback()
                raise RuntimeError(f"SQLite query error: {e} — SQL: {sql[:200]}") from e


class Database:
    """Supabase-py-style entry point: db.table("users").select("*")..."""

    def __init__(self):
        self._backend = Backend()

    def table(self, name: str) -> Query:
        return Query(self._backend, name)

    def raw(self, sql: str, params: list | None = None, table: str | None = None) -> list[dict]:
        """Run raw SQL (used by migrations/scripts)."""
        return self._backend.run(sql, params or [], table)


db = Database()
